const projects = [
  {title:"Budget Mini UAV",category:"UAV",image:"budget-mini-uav-visual.png",tag:"Beginner",summary:"Quadcopter nhỏ gọn, chi phí hợp lý cho dự án STEM đầu tiên.",stats:["30 linh kiện","<$150","CAD + Wiring"],features:["Khung carbon mini","Flight controller tích hợp ESC","Propeller guard và kiểm tra CG"]},
  {title:"Long Range UAV",category:"UAV",image:"long-range-uav-visual.png",tag:"Advanced",summary:"Máy bay cánh bằng tầm xa cho khảo sát và nhiệm vụ tự hành.",stats:["39 linh kiện","Fixed-wing","CFD 2D/3D"],features:["Autopilot và telemetry","Tối ưu endurance","Mô phỏng khí động học"]},
  {title:"Mother UAV Carrier",category:"UAV",image:"mother-uav-visual.png",tag:"Concept",summary:"Nền tảng UAV mẹ mang sáu micro-UAV cho nghiên cứu dân sự.",stats:["6 docking cells","Carrier","Research"],features:["Hệ thống docking","Quản lý nguồn","Bố trí service rack"]},
  {title:"VTOL Survey Drone",category:"UAV",image:"vtol-survey-visual.png",tag:"Advanced",summary:"Quadplane cất hạ cánh thẳng đứng dành cho khảo sát bản đồ.",stats:["26 linh kiện","VTOL","Mapping"],features:["Chuyển tiếp hover–cruise","Camera mapping","Thiết kế cánh carbon"]},
  {title:"FPV Racing Drone",category:"UAV",image:"fpv-racing-drone-visual.png",tag:"Popular",summary:"Drone đua 5-inch 6S phản hồi nhanh, dễ sửa và tinh chỉnh.",stats:["5 inch","6S LiPo","FPV"],features:["H7 flight controller","PID và filtering","Khung carbon bảo trì nhanh"]},
  {title:"Cinematic Drone",category:"UAV",image:"filming-drone-visual.png",tag:"Creator",summary:"Nền tảng quay phim 7-inch với mount chống rung cho action camera.",stats:["7 inch","GoPro","GPS"],features:["Deadcat frame","Vibration isolation","Cân bằng payload"]},
  {title:"Observation Multirotor",category:"UAV",image:"observation-multirotor-visual.png",tag:"Survey",summary:"Multirotor thời lượng bay dài cho inspection và monitoring.",stats:["Long endurance","Gimbal","Telemetry"],features:["Camera stabilized","Battery optimization","Mission planning"]},
  {title:"Dragonfly Ornithopter",category:"UAV",image:"dragonfly-ornithopter-visual.png",tag:"Experimental",summary:"Thiết bị bay vỗ cánh lấy cảm hứng từ chuồn chuồn cho nghiên cứu STEM.",stats:["Flapping wing","Micro","Bio-inspired"],features:["Cơ cấu vỗ đối xứng","Khung siêu nhẹ","Phân tích chuyển động"]},
  {title:"Smart Mobile Robot",category:"Robot",image:"smart-mobile-robot-visual.png",tag:"Beginner",summary:"Robot tự hành học line-following, tránh vật cản và cảm biến môi trường.",stats:["ESP32","4WD","Sensors"],features:["PID line following","Ultrasonic avoidance","Modular sensor deck"]},
  {title:"Companion Bot",category:"Robot",image:"companion-bot-visual.png",tag:"Friendly",summary:"Robot để bàn biểu cảm với màn hình, cảm biến và chuyển động.",stats:["ESP32-S3","Display","Interactive"],features:["Khuôn mặt động","Cảm biến môi trường","Enclosure dễ in 3D"]},
  {title:"Wall-E Robot",category:"Robot",image:"walle-robot-visual.png",tag:"Popular",summary:"Robot companion bánh xích với vision, voice và cánh tay biểu cảm.",stats:["Vision","Voice","Tracked"],features:["Obstacle avoidance","Đầu và tay chuyển động","Computer vision"]},
  {title:"Quadruped Robodog",category:"Robot",image:"robodog-visual.png",tag:"Advanced",summary:"Robot bốn chân 12 DOF với joint motor BLDC và mạng CAN.",stats:["12 DOF","CAN bus","Gait"],features:["Inverse kinematics","Gait controller","Mass balancing"]},
  {title:"Humanoid Research Robot",category:"Robot",image:"humanoid-robot-visual.png",tag:"Research",summary:"Nền tảng humanoid cho perception, balance và human-robot interaction.",stats:["RGB-D","Balance","AI compute"],features:["Dynamixel joints","Foot pressure arrays","Whole-body control"]},
  {title:"SCARA Arm",category:"Robot",image:"scara-arm-robot-visual.png",tag:"Workshop",summary:"Cánh tay robot bốn trục cho thao tác và tự động hóa để bàn.",stats:["4 axis","Gripper","Repeatable"],features:["Joint calibration","Backlash control","Two-finger gripper"]},
  {title:"Autonomous Survey USV",category:"Marine",image:"usv-visual.png",tag:"Survey",summary:"Tàu mặt nước tự hành cho thủy đạc và quan trắc môi trường.",stats:["Autonomous","Sonar","Water quality"],features:["Twin-hull platform","Sonar gondola","Waypoint navigation"]},
  {title:"RC Camera Boat",category:"Marine",image:"rc-boat-visual.png",tag:"Explorer",summary:"Thuyền điều khiển từ xa với camera dưới nước có dây tời.",stats:["Brushless","Camera","Winch"],features:["Hull chống nước","Camera pod","Rudder steering"]},
  {title:"Mini Submarine ROV",category:"Marine",image:"mini-submarine-visual.png",tag:"Explorer",summary:"ROV kín nước nhỏ gọn cho khám phá và quan sát dưới nước.",stats:["ROV","2 thrusters","Tether"],features:["Pressure hull","Neutral buoyancy","Live camera"]},
  {title:"DIY 3D Printer",category:"Workshop",image:"printer-3d-visual.png",tag:"Maker",summary:"Máy in FDM Cartesian ngân sách thấp với hệ sinh thái linh kiện phổ biến.",stats:["FDM","Cartesian","Open source"],features:["RAMPS controller","Heated bed","Printable upgrades"]},
  {title:"Modular Wind Harvester",category:"IoT",image:"modular-wind-harvester-visual.png",tag:"Energy",summary:"Máy thu năng lượng gió với MPPT và lưu trữ supercapacitor.",stats:["BLDC","MPPT","ESP32"],features:["Blade pitch tuning","Energy telemetry","Modular mast"]},
  {title:"Smart Garden",category:"IoT",image:"garden-irrigation-visual.png",tag:"Home",summary:"Hệ tưới sáu vùng theo độ ẩm đất, thời tiết và lịch tự động.",stats:["6 zones","ESP32","Automation"],features:["Soil sensing","Valve control","Weatherproof enclosure"]},
  {title:"AR Smart Glasses",category:"IoT",image:"ar-glasses-visual.png",tag:"Wearable",summary:"Kính AR ESP32-S3 với OLED, camera, IMU và âm thanh.",stats:["OLED","IMU","Camera"],features:["Magnifier optics","Head tracking","Balanced temples"]},
  {title:"Plasma Thruster Study",category:"Workshop",image:"plasma-thruster-visual.png",tag:"Concept",summary:"Tham chiếu khái niệm cho nghiên cứu propulsion và qualification.",stats:["Conceptual","HV safety","Research"],features:["Magnetic nozzle","Xenon feed concept","Safety interlocks"]}
];

const grid=document.querySelector("#project-grid"),search=document.querySelector("#search"),count=document.querySelector("#result-count"),dialog=document.querySelector("#project-dialog");
let activeFilter="All";
function render(){const q=search.value.trim().toLowerCase();const list=projects.filter(p=>(activeFilter==="All"||p.category===activeFilter)&&(`${p.title} ${p.summary} ${p.features.join(" ")}`.toLowerCase().includes(q)));count.textContent=list.length;grid.innerHTML=list.map((p,i)=>`<article class="project-card" style="--delay:${i*25}ms" tabindex="0" data-project="${projects.indexOf(p)}"><div class="project-image"><img src="diy-app/public/${p.image}" alt="${p.title}" loading="lazy"><span>${p.tag}</span><button aria-label="Xem ${p.title}">↗</button></div><div class="project-copy"><small>${p.category.toUpperCase()}</small><h3>${p.title}</h3><p>${p.summary}</p><div>${p.stats.map(s=>`<span>${s}</span>`).join("")}</div></div></article>`).join("")||`<div class="empty"><b>Không tìm thấy dự án phù hợp.</b><p>Thử một từ khóa hoặc danh mục khác.</p></div>`}
function setFilter(value){activeFilter=value;document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b.dataset.filter===value));render();document.querySelector("#projects").scrollIntoView({behavior:"smooth"})}
function openProject(index){const p=projects[index],toggle=document.querySelector("#dialog-view-toggle");document.querySelector("#dialog-image").src=`diy-app/public/${p.image}`;document.querySelector("#dialog-title").textContent=p.title;document.querySelector("#dialog-category").textContent=`${p.category} · ${p.tag}`;document.querySelector("#dialog-description").textContent=p.summary;document.querySelector("#dialog-stats").innerHTML=p.stats.map(s=>`<span><b>${s}</b><small>PROJECT SPEC</small></span>`).join("");document.querySelector("#dialog-features").innerHTML=p.features.map(x=>`<li>${x}</li>`).join("");dialog.classList.remove("show-3d");toggle.textContent="XEM 3D";toggle.hidden=false;dialog.showModal();window.dispatchEvent(new CustomEvent("aerodiy:open-model",{detail:{index}}))}
document.addEventListener("click",e=>{const scroll=e.target.closest("[data-scroll]");if(scroll){document.querySelector(`#${scroll.dataset.scroll}`).scrollIntoView({behavior:"smooth"});document.querySelector("#sidebar").classList.remove("open")}const filter=e.target.closest("[data-filter]");if(filter)setFilter(filter.dataset.filter);const cat=e.target.closest("[data-category]");if(cat)setFilter(cat.dataset.category);const card=e.target.closest("[data-project]");if(card)openProject(Number(card.dataset.project));if(e.target.matches(".dialog-close,.dialog-close-button"))dialog.close()});
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.querySelector("#projects").scrollIntoView({behavior:"smooth"});setTimeout(()=>search.focus(),450)}if(e.key==="Enter"&&e.target.matches("[data-project]"))openProject(Number(e.target.dataset.project))});
search.addEventListener("input",render);document.querySelector("#clear-filter").onclick=()=>{search.value="";setFilter("All")};document.querySelector("#menu").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");document.querySelector("#theme").onclick=()=>document.body.classList.toggle("soft");document.querySelector("#dialog-start").onclick=()=>{dialog.close();document.querySelector("#workflow").scrollIntoView({behavior:"smooth"})};
document.querySelector("#dialog-view-toggle").onclick=()=>{const active=dialog.classList.toggle("show-3d");document.querySelector("#dialog-view-toggle").textContent=active?"XEM ẢNH":"XEM 3D";if(active)window.dispatchEvent(new Event("aerodiy:resize-model"))};
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.scroll===entry.target.id))}}),{rootMargin:"-35% 0px -55%"});document.querySelectorAll("main>section[id]").forEach(s=>observer.observe(s));render();
